### PR TITLE
Add server prefix support

### PR DESCRIPTION
**Pull request by schnubor**
Hi!

Currently if you want to server the site from a `/test` subdirectory it won't work. This PR adds support for an **optional** server `prefix` config since it currently doesn't support it. I'm also adding this in regards to this Elderjs issue/PR regarding the server prefix: https://github.com/Elderjs/elderjs/pull/128 

If a `prefix` is configured, all the `.woff` files will be downloaded to a directory named after the prefix, e.g. `/test`, and rewrite the inline styles accordingly. If no prefix is specified, everything works as usual.

I also updated the README a little to also highlight the existing `swap` config, that is quite important in regards of pagespeed imho. `subsets` seems to be deprecated, since it will always download all subsets no matter what subsets are specified (https://github.com/google/fonts/issues/384)

Would be nice if you could have a look at this @kevmodrome !

Thanks,
Christian

### CODE REVIEW

**Comment by schnubor** [comment]
@kevmodrome https://github.com/Elderjs/elderjs/pull/128 got merged, so I think it would be nice if this plugin would support prefixes as well :)

**Comment by kevmodrome** [comment]
Sorry for the slow merge. Thanks!

**Comment by schnubor** [comment]
no worries, thanks :)

**Comment by schnubor** [comment]
Ah one more thing, can you publish to npm?

**Pull request merged**
